language: generic 
sudo: required
services:
    - docker

before_install:
    - docker build -t aaron160487/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true aaron160487/docker-react npm run test

deploy:
   provider: elasticbeanstalk
   region: "us-east-1"
   app: "Dockerapp"
   env: "Dockerapp-env1"
   bucket_name: "elasticbeanstalk-us-east-2-781077946232"
   bucket_path: "Dockerapp"
   on:
    branch: master
   access_key_id: "$AWS_ACCESS_KEY"
   secret_access_key: "$AWS_SECRET_KEY"

  